INSERT INTO recipes (name, category, description, servings, prep_time_minutes) VALUES ('Asian Braised Pork, white rice, Rainbow carrots', 'prepared_meal', 'Asian Braised Pork, white rice, Rainbow carrots', 1, 30);
INSERT INTO recipes (name, category, description, servings, prep_time_minutes) VALUES ('BBQ Orange Chicken with Gochujang Potatoes & Carroots', 'prepared_meal', 'BBQ Orange Chicken with Gochujang Potatoes & Carroots', 1, 30);
INSERT INTO recipes (name, category, description, servings, prep_time_minutes) VALUES ('BBQ chicken Potatoes, Zucchini', 'prepared_meal', 'BBQ chicken Potatoes, Zucchini', 1, 30);
INSERT INTO recipes (name, category, description, servings, prep_time_minutes) VALUES ('BBQ pulled Porc, Potatoes, Green Beans', 'prepared_meal', 'BBQ pulled Porc, Potatoes, Green Beans', 1, 30);
INSERT INTO recipes (name, category, description, servings, prep_time_minutes) VALUES ('Balsamic Braised Beef with Potatoes & Mixed Veggies', 'prepared_meal', 'Balsamic Braised Beef with Potatoes & Mixed Veggies', 1, 30);
INSERT INTO recipes (name, category, description, servings, prep_time_minutes) VALUES ('Balsamic chicken strawberry feta', 'prepared_meal', 'Balsamic chicken strawberry feta', 1, 30);
INSERT INTO recipes (name, category, description, servings, prep_time_minutes) VALUES ('Beef Kefta Turmeric Rice Chickpeas Peppers', 'prepared_meal', 'Beef Kefta Turmeric Rice Chickpeas Peppers', 1, 30);
INSERT INTO recipes (name, category, description, servings, prep_time_minutes) VALUES ('Beef Kefta, lemon dill rice, Peppers & Yogurt sauce', 'prepared_meal', 'Beef Kefta, lemon dill rice, Peppers & Yogurt sauce', 1, 30);
INSERT INTO recipes (name, category, description, servings, prep_time_minutes) VALUES ('Blackened chicken quinoa sweet potato bowl, parsley cauliflower', 'prepared_meal', 'Blackened chicken quinoa sweet potato bowl, parsley cauliflower', 1, 30);
INSERT INTO recipes (name, category, description, servings, prep_time_minutes) VALUES ('Braised beef & rice', 'prepared_meal', 'Braised beef & rice', 1, 30);
INSERT INTO recipes (name, category, description, servings, prep_time_minutes) VALUES ('Braised french chuck Potatoes Cauliflower', 'prepared_meal', 'Braised french chuck Potatoes Cauliflower', 1, 30);
INSERT INTO recipes (name, category, description, servings, prep_time_minutes) VALUES ('Carnitas Pork, Corn and Potatoes', 'prepared_meal', 'Carnitas Pork, Corn and Potatoes', 1, 30);
INSERT INTO recipes (name, category, description, servings, prep_time_minutes) VALUES ('Chicken & Pasta Al Limone with zucchini', 'prepared_meal', 'Chicken & Pasta Al Limone with zucchini', 1, 30);
INSERT INTO recipes (name, category, description, servings, prep_time_minutes) VALUES ('Chicken Chimichurri', 'prepared_meal', 'Chicken Chimichurri', 1, 30);
INSERT INTO recipes (name, category, description, servings, prep_time_minutes) VALUES ('Chicken Chimichurri Sweet Potatoes', 'prepared_meal', 'Chicken Chimichurri Sweet Potatoes', 1, 30);
INSERT INTO recipes (name, category, description, servings, prep_time_minutes) VALUES ('Chicken Fried Rice', 'prepared_meal', 'Chicken Fried Rice', 1, 30);
INSERT INTO recipes (name, category, description, servings, prep_time_minutes) VALUES ('Chicken Fried Rice (Broccoli, Edamame, carrots)', 'prepared_meal', 'Chicken Fried Rice (Broccoli, Edamame, carrots)', 1, 30);
INSERT INTO recipes (name, category, description, servings, prep_time_minutes) VALUES ('Chicken Kefta Parsley Rice', 'prepared_meal', 'Chicken Kefta Parsley Rice', 1, 30);
INSERT INTO recipes (name, category, description, servings, prep_time_minutes) VALUES ('Chicken Kefta Pita and Mixed Vaggies', 'prepared_meal', 'Chicken Kefta Pita and Mixed Vaggies', 1, 30);
INSERT INTO recipes (name, category, description, servings, prep_time_minutes) VALUES ('Chicken Kefta, Lemon Dill Potatoes , Broccoli, Yogurt Sauce', 'prepared_meal', 'Chicken Kefta, Lemon Dill Potatoes , Broccoli, Yogurt Sauce', 1, 30);
INSERT INTO recipes (name, category, description, servings, prep_time_minutes) VALUES ('Chicken Kefta, Pita, Hummus, Peppers & Red onions', 'prepared_meal', 'Chicken Kefta, Pita, Hummus, Peppers & Red onions', 1, 30);
INSERT INTO recipes (name, category, description, servings, prep_time_minutes) VALUES ('Chicken Orzo Salad', 'prepared_meal', 'Chicken Orzo Salad', 1, 30);
INSERT INTO recipes (name, category, description, servings, prep_time_minutes) VALUES ('Chicken Pasta', 'prepared_meal', 'Chicken Pasta', 1, 30);
INSERT INTO recipes (name, category, description, servings, prep_time_minutes) VALUES ('Chicken Peruvian', 'prepared_meal', 'Chicken Peruvian', 1, 30);
INSERT INTO recipes (name, category, description, servings, prep_time_minutes) VALUES ('Chicken Pesto Pasta Salad tomatoes', 'prepared_meal', 'Chicken Pesto Pasta Salad tomatoes', 1, 30);
INSERT INTO recipes (name, category, description, servings, prep_time_minutes) VALUES ('Chicken Potatoes Carrots', 'prepared_meal', 'Chicken Potatoes Carrots', 1, 30);
INSERT INTO recipes (name, category, description, servings, prep_time_minutes) VALUES ('Chicken Potatoes and Carrottes', 'prepared_meal', 'Chicken Potatoes and Carrottes', 1, 30);
INSERT INTO recipes (name, category, description, servings, prep_time_minutes) VALUES ('Chicken Potatoess arrots', 'prepared_meal', 'Chicken Potatoess arrots', 1, 30);
INSERT INTO recipes (name, category, description, servings, prep_time_minutes) VALUES ('Chicken Quinoa Sweet Potato Bowl', 'prepared_meal', 'Chicken Quinoa Sweet Potato Bowl', 1, 30);
INSERT INTO recipes (name, category, description, servings, prep_time_minutes) VALUES ('Chicken Rice and Peppers', 'prepared_meal', 'Chicken Rice and Peppers', 1, 30);
INSERT INTO recipes (name, category, description, servings, prep_time_minutes) VALUES ('Chicken al pastor with cilantro lime rice, corn & bean salad', 'prepared_meal', 'Chicken al pastor with cilantro lime rice, corn & bean salad', 1, 30);
INSERT INTO recipes (name, category, description, servings, prep_time_minutes) VALUES ('Chicken fried Rice', 'prepared_meal', 'Chicken fried Rice', 1, 30);
INSERT INTO recipes (name, category, description, servings, prep_time_minutes) VALUES ('Chicken fried rice', 'prepared_meal', 'Chicken fried rice', 1, 30);
INSERT INTO recipes (name, category, description, servings, prep_time_minutes) VALUES ('Chicken with roasted potatoes and peppers', 'prepared_meal', 'Chicken with roasted potatoes and peppers', 1, 30);
INSERT INTO recipes (name, category, description, servings, prep_time_minutes) VALUES ('Chipotle lime Chicken Taco Bowl (Pico)', 'prepared_meal', 'Chipotle lime Chicken Taco Bowl (Pico)', 1, 30);
INSERT INTO recipes (name, category, description, servings, prep_time_minutes) VALUES ('Coffee marinated steak, Potatoes & Green Beans', 'prepared_meal', 'Coffee marinated steak, Potatoes & Green Beans', 1, 30);
INSERT INTO recipes (name, category, description, servings, prep_time_minutes) VALUES ('Creamy Ground turkey Pasta with zucchini', 'prepared_meal', 'Creamy Ground turkey Pasta with zucchini', 1, 30);
INSERT INTO recipes (name, category, description, servings, prep_time_minutes) VALUES ('Creamy Lemon Spinach Turkey Pasta', 'prepared_meal', 'Creamy Lemon Spinach Turkey Pasta', 1, 30);
INSERT INTO recipes (name, category, description, servings, prep_time_minutes) VALUES ('Creamy Tomato Garlic Pasta, Tuscan Chicken, Zucchini', 'prepared_meal', 'Creamy Tomato Garlic Pasta, Tuscan Chicken, Zucchini', 1, 30);
INSERT INTO recipes (name, category, description, servings, prep_time_minutes) VALUES ('Cuban Mojo Porc Rice bowl with corn & Bean salad Aji verde', 'prepared_meal', 'Cuban Mojo Porc Rice bowl with corn & Bean salad Aji verde', 1, 30);
INSERT INTO recipes (name, category, description, servings, prep_time_minutes) VALUES ('Garlic Spinach Turkey Meatballs, Lemon Parsley rice, Mixed veggies', 'prepared_meal', 'Garlic Spinach Turkey Meatballs, Lemon Parsley rice, Mixed veggies', 1, 30);
INSERT INTO recipes (name, category, description, servings, prep_time_minutes) VALUES ('Ginger Lime Ground Turkey with coconut rice & Asparagus & Peppers', 'prepared_meal', 'Ginger Lime Ground Turkey with coconut rice & Asparagus & Peppers', 1, 30);
INSERT INTO recipes (name, category, description, servings, prep_time_minutes) VALUES ('Ginger Orange shredded beef sweet potato bowl, asparagus', 'prepared_meal', 'Ginger Orange shredded beef sweet potato bowl, asparagus', 1, 30);
INSERT INTO recipes (name, category, description, servings, prep_time_minutes) VALUES ('Ginger orange braised beef, Rice, Green beans', 'prepared_meal', 'Ginger orange braised beef, Rice, Green beans', 1, 30);
INSERT INTO recipes (name, category, description, servings, prep_time_minutes) VALUES ('Greek Chicken Quinoa Salad (Carrots, Peppers, zucchini)', 'prepared_meal', 'Greek Chicken Quinoa Salad (Carrots, Peppers, zucchini)', 1, 30);
INSERT INTO recipes (name, category, description, servings, prep_time_minutes) VALUES ('Greek Ckicken Dill Feta Vinaigrette & Orzo', 'prepared_meal', 'Greek Ckicken Dill Feta Vinaigrette & Orzo', 1, 30);
INSERT INTO recipes (name, category, description, servings, prep_time_minutes) VALUES ('Greek Ground Turkey', 'prepared_meal', 'Greek Ground Turkey', 1, 30);
INSERT INTO recipes (name, category, description, servings, prep_time_minutes) VALUES ('Greek Ground Turkey Yellow Rice Peppers Yogurt Sauce', 'prepared_meal', 'Greek Ground Turkey Yellow Rice Peppers Yogurt Sauce', 1, 30);
INSERT INTO recipes (name, category, description, servings, prep_time_minutes) VALUES ('Greek Ground turkey yellow rice mixed veggies', 'prepared_meal', 'Greek Ground turkey yellow rice mixed veggies', 1, 30);
INSERT INTO recipes (name, category, description, servings, prep_time_minutes) VALUES ('Ground Beef Gochujang White Rice Vaggies', 'prepared_meal', 'Ground Beef Gochujang White Rice Vaggies', 1, 30);
INSERT INTO recipes (name, category, description, servings, prep_time_minutes) VALUES ('Ground Beef Rice and Beans and corn', 'prepared_meal', 'Ground Beef Rice and Beans and corn', 1, 30);
INSERT INTO recipes (name, category, description, servings, prep_time_minutes) VALUES ('Ground Turkey Pasta Zucchini', 'prepared_meal', 'Ground Turkey Pasta Zucchini', 1, 30);
INSERT INTO recipes (name, category, description, servings, prep_time_minutes) VALUES ('Ground Turkey, Rice, Peppers', 'prepared_meal', 'Ground Turkey, Rice, Peppers', 1, 30);
INSERT INTO recipes (name, category, description, servings, prep_time_minutes) VALUES ('Ground beef Korean carrrots', 'prepared_meal', 'Ground beef Korean carrrots', 1, 30);
INSERT INTO recipes (name, category, description, servings, prep_time_minutes) VALUES ('Ground beef chimichuri, Rice and Bean and Corn Salad', 'prepared_meal', 'Ground beef chimichuri, Rice and Bean and Corn Salad', 1, 30);
INSERT INTO recipes (name, category, description, servings, prep_time_minutes) VALUES ('Ground beef chimichurri sweet potato', 'prepared_meal', 'Ground beef chimichurri sweet potato', 1, 30);
INSERT INTO recipes (name, category, description, servings, prep_time_minutes) VALUES ('Ground beef chimichurri sweet potato trio veggie', 'prepared_meal', 'Ground beef chimichurri sweet potato trio veggie', 1, 30);
INSERT INTO recipes (name, category, description, servings, prep_time_minutes) VALUES ('Ground beef sweet potato bowl with broccoli', 'prepared_meal', 'Ground beef sweet potato bowl with broccoli', 1, 30);
INSERT INTO recipes (name, category, description, servings, prep_time_minutes) VALUES ('Honey Lime chicken & Rice, corn & mango salsa', 'prepared_meal', 'Honey Lime chicken & Rice, corn & mango salsa', 1, 30);
INSERT INTO recipes (name, category, description, servings, prep_time_minutes) VALUES ('Italian Chicken and Pasta', 'prepared_meal', 'Italian Chicken and Pasta', 1, 30);
INSERT INTO recipes (name, category, description, servings, prep_time_minutes) VALUES ('Jamaican Pineapple Jerk Chicken With Rice Peppers', 'prepared_meal', 'Jamaican Pineapple Jerk Chicken With Rice Peppers', 1, 30);
INSERT INTO recipes (name, category, description, servings, prep_time_minutes) VALUES ('Kale Quinoa Salad with beef meatballs', 'prepared_meal', 'Kale Quinoa Salad with beef meatballs', 1, 30);
INSERT INTO recipes (name, category, description, servings, prep_time_minutes) VALUES ('Korean BBQ Beef with Broccoli & Sweet Potato Trio', 'prepared_meal', 'Korean BBQ Beef with Broccoli & Sweet Potato Trio', 1, 30);
INSERT INTO recipes (name, category, description, servings, prep_time_minutes) VALUES ('Korean Ground Beef Sweet Potato Bowl with broccoli', 'prepared_meal', 'Korean Ground Beef Sweet Potato Bowl with broccoli', 1, 30);
INSERT INTO recipes (name, category, description, servings, prep_time_minutes) VALUES ('Korean Ground beef, Sweet potato Trio, Broccoli', 'prepared_meal', 'Korean Ground beef, Sweet potato Trio, Broccoli', 1, 30);
INSERT INTO recipes (name, category, description, servings, prep_time_minutes) VALUES ('Lemon Chicken Zaatar potatoes, Veggies', 'prepared_meal', 'Lemon Chicken Zaatar potatoes, Veggies', 1, 30);
INSERT INTO recipes (name, category, description, servings, prep_time_minutes) VALUES ('Marinated Steak & Potatoes, Broccoli', 'prepared_meal', 'Marinated Steak & Potatoes, Broccoli', 1, 30);
INSERT INTO recipes (name, category, description, servings, prep_time_minutes) VALUES ('Marinated Steak, Garlic & Herbes Potatoes, Green beans', 'prepared_meal', 'Marinated Steak, Garlic & Herbes Potatoes, Green beans', 1, 30);
INSERT INTO recipes (name, category, description, servings, prep_time_minutes) VALUES ('Mediteranean Ground Beef stir fry with mixed veggies', 'prepared_meal', 'Mediteranean Ground Beef stir fry with mixed veggies', 1, 30);
INSERT INTO recipes (name, category, description, servings, prep_time_minutes) VALUES ('Mediteranean Ground Turkey, Quinoa&Tomatoes hot honey pickled onions', 'prepared_meal', 'Mediteranean Ground Turkey, Quinoa&Tomatoes hot honey pickled onions', 1, 30);
INSERT INTO recipes (name, category, description, servings, prep_time_minutes) VALUES ('Mojo Porc, Yuka Southwestern corn & Sauce', 'prepared_meal', 'Mojo Porc, Yuka Southwestern corn & Sauce', 1, 30);
INSERT INTO recipes (name, category, description, servings, prep_time_minutes) VALUES ('Mustard Chicken & Potatoes Asparagus', 'prepared_meal', 'Mustard Chicken & Potatoes Asparagus', 1, 30);
INSERT INTO recipes (name, category, description, servings, prep_time_minutes) VALUES ('Orange Cilantro Chicken, Potatoes & Peppers, Aji verde', 'prepared_meal', 'Orange Cilantro Chicken, Potatoes & Peppers, Aji verde', 1, 30);
INSERT INTO recipes (name, category, description, servings, prep_time_minutes) VALUES ('Orange Cilantro chicken Quinoa Salad', 'prepared_meal', 'Orange Cilantro chicken Quinoa Salad', 1, 30);
INSERT INTO recipes (name, category, description, servings, prep_time_minutes) VALUES ('Orzo salad chicken', 'prepared_meal', 'Orzo salad chicken', 1, 30);
INSERT INTO recipes (name, category, description, servings, prep_time_minutes) VALUES ('Pasta Salad Grilled chicken', 'prepared_meal', 'Pasta Salad Grilled chicken', 1, 30);
INSERT INTO recipes (name, category, description, servings, prep_time_minutes) VALUES ('Pasta turkey and Zucchini', 'prepared_meal', 'Pasta turkey and Zucchini', 1, 30);
INSERT INTO recipes (name, category, description, servings, prep_time_minutes) VALUES ('Pesto Chicken & Potatoes, Asparagus', 'prepared_meal', 'Pesto Chicken & Potatoes, Asparagus', 1, 30);
INSERT INTO recipes (name, category, description, servings, prep_time_minutes) VALUES ('Pesto Chicken, Potatoes, Veggies', 'prepared_meal', 'Pesto Chicken, Potatoes, Veggies', 1, 30);
INSERT INTO recipes (name, category, description, servings, prep_time_minutes) VALUES ('Porc Tenderloin with creamy mustard Sauce Potatoes & Cauliflower', 'prepared_meal', 'Porc Tenderloin with creamy mustard Sauce Potatoes & Cauliflower', 1, 30);
INSERT INTO recipes (name, category, description, servings, prep_time_minutes) VALUES ('Porc Tenderloines, Potatoes asperagus', 'prepared_meal', 'Porc Tenderloines, Potatoes asperagus', 1, 30);
INSERT INTO recipes (name, category, description, servings, prep_time_minutes) VALUES ('Quinoa Sweet Potato, Chicken with honey mustard', 'prepared_meal', 'Quinoa Sweet Potato, Chicken with honey mustard', 1, 30);
INSERT INTO recipes (name, category, description, servings, prep_time_minutes) VALUES ('Quinoa beef Bowl', 'prepared_meal', 'Quinoa beef Bowl', 1, 30);
INSERT INTO recipes (name, category, description, servings, prep_time_minutes) VALUES ('Slow Cooked Orange ginger beef & rice with mixed veggis', 'prepared_meal', 'Slow Cooked Orange ginger beef & rice with mixed veggis', 1, 30);
INSERT INTO recipes (name, category, description, servings, prep_time_minutes) VALUES ('Slow cooked balsamic chuck with', 'prepared_meal', 'Slow cooked balsamic chuck with', 1, 30);
INSERT INTO recipes (name, category, description, servings, prep_time_minutes) VALUES ('Slow cooked beef Potatoes Veggie', 'prepared_meal', 'Slow cooked beef Potatoes Veggie', 1, 30);
INSERT INTO recipes (name, category, description, servings, prep_time_minutes) VALUES ('Slow cooked beef with rice & veggies', 'prepared_meal', 'Slow cooked beef with rice & veggies', 1, 30);
INSERT INTO recipes (name, category, description, servings, prep_time_minutes) VALUES ('Spinach Garlic Turkey Meatballs, Orzo Salad (Peppers, sundried, zucchini)', 'prepared_meal', 'Spinach Garlic Turkey Meatballs, Orzo Salad (Peppers, sundried, zucchini)', 1, 30);
INSERT INTO recipes (name, category, description, servings, prep_time_minutes) VALUES ('Spinach Garlic Turkey Meatballs, Potatoes, Asparagus', 'prepared_meal', 'Spinach Garlic Turkey Meatballs, Potatoes, Asparagus', 1, 30);
INSERT INTO recipes (name, category, description, servings, prep_time_minutes) VALUES ('Spinach garlic turkey meatballs', 'prepared_meal', 'Spinach garlic turkey meatballs', 1, 30);
INSERT INTO recipes (name, category, description, servings, prep_time_minutes) VALUES ('Steak Potatoes, Green Beans', 'prepared_meal', 'Steak Potatoes, Green Beans', 1, 30);
INSERT INTO recipes (name, category, description, servings, prep_time_minutes) VALUES ('Steak Shawarma, Yelllow Rice, Chickpeas, Peppers', 'prepared_meal', 'Steak Shawarma, Yelllow Rice, Chickpeas, Peppers', 1, 30);
INSERT INTO recipes (name, category, description, servings, prep_time_minutes) VALUES ('Steak Sweet Potatoes Broccoli', 'prepared_meal', 'Steak Sweet Potatoes Broccoli', 1, 30);
INSERT INTO recipes (name, category, description, servings, prep_time_minutes) VALUES ('Steak Taco Bowl', 'prepared_meal', 'Steak Taco Bowl', 1, 30);
INSERT INTO recipes (name, category, description, servings, prep_time_minutes) VALUES ('Steak Taco Bowl Peppers', 'prepared_meal', 'Steak Taco Bowl Peppers', 1, 30);
INSERT INTO recipes (name, category, description, servings, prep_time_minutes) VALUES ('Steak, Potatoes, asparagus', 'prepared_meal', 'Steak, Potatoes, asparagus', 1, 30);
INSERT INTO recipes (name, category, description, servings, prep_time_minutes) VALUES ('Steak, Potatoes, mixed veggies', 'prepared_meal', 'Steak, Potatoes, mixed veggies', 1, 30);
INSERT INTO recipes (name, category, description, servings, prep_time_minutes) VALUES ('Sweet Potato ground beef corn', 'prepared_meal', 'Sweet Potato ground beef corn', 1, 30);
INSERT INTO recipes (name, category, description, servings, prep_time_minutes) VALUES ('Sweet potato chimichurri beef bowl, corn & Zucchini, Pico', 'prepared_meal', 'Sweet potato chimichurri beef bowl, corn & Zucchini, Pico', 1, 30);
INSERT INTO recipes (name, category, description, servings, prep_time_minutes) VALUES ('Thai basil ground beef Coconut Rice Carrots/wsperge', 'prepared_meal', 'Thai basil ground beef Coconut Rice Carrots/wsperge', 1, 30);
INSERT INTO recipes (name, category, description, servings, prep_time_minutes) VALUES ('Turkey Meatballs Potatoes Zuccini', 'prepared_meal', 'Turkey Meatballs Potatoes Zuccini', 1, 30);
INSERT INTO recipes (name, category, description, servings, prep_time_minutes) VALUES ('Tuscan Chicken with orzo salad', 'prepared_meal', 'Tuscan Chicken with orzo salad', 1, 30);
INSERT INTO recipes (name, category, description, servings, prep_time_minutes) VALUES ('chicken shawarma', 'prepared_meal', 'chicken shawarma', 1, 30);