require('dotenv').config()
const express = require('express')
const cors = require('cors')
const helmet = require('helmet')

const authRoutes = require('./routes/auth')
const mealsRoutes = require('./routes/meals')
const weeklyMenusRoutes = require('./routes/weeklyMenus')
const deliveryZonesRoutes = require('./routes/deliveryZones')
const boxesRoutes = require('./routes/boxes')
const dietProfilesRoutes = require('./routes/dietProfiles')
const mealLogsRoutes = require('./routes/mealLogs')
const xpRoutes = require('./routes/xp')
const bulkDiscountsRoutes = require('./routes/bulkDiscounts')
const paymentsRoutes = require('./routes/payments')
const adminRecipesRoutes = require('./routes/admin/adminRecipes')
const adminMenuPlannerRoutes = require('./routes/admin/adminMenuPlanner')
const adminInventoryRoutes = require('./routes/admin/adminInventory')
const adminReceiptsRoutes = require('./routes/admin/adminReceipts')
const adminOrdersRoutes = require('./routes/admin/adminOrders')
const adminPrepRoutes = require('./routes/admin/adminPrep')
const adminCustomersRoutes = require('./routes/admin/adminCustomers')
const adminExpensesRoutes = require('./routes/admin/adminExpenses')
const adminProductsRoutes = require('./routes/admin/adminProducts')
const adminReceiptSyncRoutes = require('./routes/admin/adminReceiptSync')
const adminReceiptReviewRoutes = require('./routes/admin/adminReceiptReview')
const adminReceiptReadRoutes = require('./routes/admin/adminReceiptRead')
const adminReportsRoutes = require('./routes/admin/adminReports')
const taskManagementRoutes = require('./routes/admin/taskManagement')
const taskManagementAutoRoutes = require('./routes/admin/taskManagementAuto')
const taskManagementTestRoutes = require('./routes/admin/taskManagementTest')

const app = express()

app.use(helmet())
app.use(cors({ origin: '*', allowedHeaders: ['Content-Type', 'Authorization'] }))

// Stripe webhook needs raw body — must be before express.json()
app.use('/api/payments/webhook', express.raw({ type: 'application/json' }))
// Increase JSON payload limit for image uploads
app.use(express.json({ limit: '50mb' }))

app.use('/api/auth', authRoutes)
app.use('/api/meals', mealsRoutes)
app.use('/api/weekly-menus', weeklyMenusRoutes)
app.use('/api/delivery-zones', deliveryZonesRoutes)
app.use('/api/boxes', boxesRoutes)
app.use('/api/diet-profile', dietProfilesRoutes)
app.use('/api/meal-logs', mealLogsRoutes)
app.use('/api/xp', xpRoutes)
app.use('/api/bulk-discounts', bulkDiscountsRoutes)
app.use('/api/payments', paymentsRoutes)
app.use('/api/admin/recipes', adminRecipesRoutes)
app.use('/api/admin/menu-planner', adminMenuPlannerRoutes)
app.use('/api/inventory', adminInventoryRoutes)
app.use('/api/receipts', adminReceiptsRoutes)
app.use('/api/admin/orders', adminOrdersRoutes)
app.use('/api/admin/prep', adminPrepRoutes)
app.use('/api/admin/customers', adminCustomersRoutes)
app.use('/api/admin/expenses', adminExpensesRoutes)
app.use('/api/admin/products', adminProductsRoutes)
app.use('/api/admin/receipt-sync', adminReceiptSyncRoutes)
app.use('/api/admin/receipt-review', adminReceiptReviewRoutes)
app.use('/api/admin/receipt-read', adminReceiptReadRoutes)
app.use('/api/admin/reports', adminReportsRoutes)
app.use('/api/admin/task-management', taskManagementRoutes)
app.use('/api/admin/task-management-auto', taskManagementAutoRoutes)
app.use('/api/admin/task-management-test', taskManagementTestRoutes)

app.get('/health', (req, res) => res.json({ status: 'ok' }))

module.exports = app
