require('dotenv').config()
const express = require('express')
const cors = require('cors')
const helmet = require('helmet')

const authRoutes = require('./routes/auth')
const mealsRoutes = require('./routes/meals')
const weeklyMenusRoutes = require('./routes/weeklyMenus')
const deliveryZonesRoutes = require('./routes/deliveryZones')
const boxesRoutes = require('./routes/boxes')
const dietProfilesRoutes = require('./routes/dietProfiles')
const mealLogsRoutes = require('./routes/mealLogs')
const xpRoutes = require('./routes/xp')
const bulkDiscountsRoutes = require('./routes/bulkDiscounts')
const paymentsRoutes = require('./routes/payments')
const adminRecipesRoutes = require('./routes/admin/adminRecipes')
const adminRecipeImportRoutes = require('./routes/admin/adminRecipeImport')
const adminMenuPlannerRoutes = require('./routes/admin/adminMenuPlanner')
const adminInventoryRoutes = require('./routes/admin/adminInventory')
const adminOrdersRoutes = require('./routes/admin/adminOrders')
const adminPrepRoutes = require('./routes/admin/adminPrep')
const adminCustomersRoutes = require('./routes/admin/adminCustomers')
const adminCommunicationsRoutes = require('./routes/admin/adminCommunications')
const adminAutomationsRoutes = require('./routes/admin/adminAutomations')
const adminExpensesRoutes = require('./routes/admin/adminExpenses')
const adminProductsRoutes = require('./routes/admin/adminProducts')
const adminReceiptSyncRoutes = require('./routes/admin/adminReceiptSync')
const adminReceiptReadRoutes = require('./routes/admin/adminReceiptRead')
const adminReportsRoutes = require('./routes/admin/adminReports')
const adminTasksRoutes = require('./routes/admin/adminTasks')
const launchTasksRoutes = require('./routes/admin/launchTasks')
const launchDayNotesRoutes = require('./routes/admin/launchDayNotes')
const adminUsersRoutes = require('./routes/admin/adminUsers')
const adminProductionPlanRoutes = require('./routes/admin/adminProductionPlan')
const adminCookingMethodsRoutes = require('./routes/admin/adminCookingMethods')
const publicOrderingRoutes = require('./routes/publicOrdering')

const app = express()

app.use(helmet())
app.use(cors({ origin: '*', allowedHeaders: ['Content-Type', 'Authorization'] }))

// Stripe webhook needs raw body — must be before express.json()
app.use('/api/payments/webhook', express.raw({ type: 'application/json' }))
// Increase JSON payload limit for image uploads
app.use(express.json({ limit: '50mb' }))

app.use('/api/auth', authRoutes)
app.use('/api/meals', mealsRoutes)
app.use('/api/weekly-menus', weeklyMenusRoutes)
app.use('/api/delivery-zones', deliveryZonesRoutes)
app.use('/api/boxes', boxesRoutes)
app.use('/api/diet-profile', dietProfilesRoutes)
app.use('/api/meal-logs', mealLogsRoutes)
app.use('/api/xp', xpRoutes)
app.use('/api/bulk-discounts', bulkDiscountsRoutes)
app.use('/api/payments', paymentsRoutes)
app.use('/api/admin/recipes', adminRecipesRoutes)
app.use('/api/admin/recipe-import', adminRecipeImportRoutes)
app.use('/api/admin/menu-planner', adminMenuPlannerRoutes)
app.use('/api/inventory', adminInventoryRoutes)
app.use('/api/admin/orders', adminOrdersRoutes)
app.use('/api/admin/prep', adminPrepRoutes)
app.use('/api/admin/customers', adminCustomersRoutes)
app.use('/api/admin', adminCommunicationsRoutes)
app.use('/api/admin', adminAutomationsRoutes)
app.use('/api/admin/expenses', adminExpensesRoutes)
app.use('/api/admin/products', adminProductsRoutes)
app.use('/api/admin/receipt-sync', adminReceiptSyncRoutes)
app.use('/api/admin/receipt-read', adminReceiptReadRoutes)
app.use('/api/admin/reports', adminReportsRoutes)
app.use('/api/admin/tasks', adminTasksRoutes)
app.use('/api/admin/launch-tasks', launchTasksRoutes)
app.use('/api/admin/launch-day-notes', launchDayNotesRoutes)
app.use('/api/admin/users', adminUsersRoutes)
app.use('/api/admin/production-plan', adminProductionPlanRoutes)
app.use('/api/admin', adminCookingMethodsRoutes)
app.use('/api/public', publicOrderingRoutes)

app.get('/health', (req, res) => res.json({ status: 'ok' }))

module.exports = app
